#!/bin/bash
#
#
## AddSongsScipt
#
## Shell Command Scipt to:
## Pull list of song URLs to download from github
## Download MP3 audio of songs
## Push empty list to github
#
## Usage: AddSongsScript (No Command Line Arguments)
#

# Print Friendly Message
echo "ARRRR MATEY, PIRATIN' THE MUSIC"

# Navigate to this folder
cd ~/Music/.git/MusicURLs

# Update list
git pull

# Download every song in the list
for song in $(cat ./songs.txt) ; do
	youtube-dl $song
done

# Delete the list
rm ./songs.txt

# Create a new empty list
touch ./songs.txt

# Push Changes
git commit -a -m "Pulled Songs"
git push

# State Download Complete
echo "BOOTY LOOTED"